version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Checking for application.py"
      - test -f application.py || (echo "application.py missing!" && exit 1)

  build:
    commands:
      - echo "Build phase complete — no zipping needed"

artifacts:
  files:
    - '**/*'


