version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "No dependencies to install for application.py"
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo "Running pre-build checks..."

  build:
    commands:
      - echo "Packaging application..."
      - zip -r app.zip * -x "*.git*" "*.DS_Store*" "buildspec.yml" "*.zip"

artifacts:
  files:
    - app.zip
